version: '3'

services:
  db:
    image: postgis/postgis:13-3.1
    environment:
      POSTGRES_DB: webgis_db
      POSTGRES_USER: santy
      POSTGRES_PASSWORD: Password123
    ports:
      - "5432:5432"

  web:
    build: .
    command: bash -c "/wait_for_db.sh db:5432 -- python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app:/app
    ports:
        - "7777:8000"
    depends_on:
        - db
    environment:
        - DATABASE_URL=postgres://santy:Password123@db:5432/webgis_db