# Generated by Django 5.1.2 on 2024-10-11 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Region',
            new_name='State',
        ),
    ]
