# Generated by Django 5.1.2 on 2024-10-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_rename_region_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='river',
            name='layer',
        ),
        migrations.RemoveField(
            model_name='river',
            name='path',
        ),
        migrations.AlterField(
            model_name='river',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
